name: Typos

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:
jobs:
  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.47.0
